set( PACKAGE_VERSION_MAJOR 0 )
set( PACKAGE_VERSION_MINOR 0 )
set( PACKAGE_VERSION_PATCH 0 )

set( PACKAGE_VERSION
	"${PACKAGE_VERSION_MAJOR}.${PACKAGE_VERSION_MINOR}.${PACKAGE_VERSION_PATCH}"
	)

if( PACKAGE_VERSION VERSION_LESS PACKAGE_FIND_VERSION )
	set( PACKAGE_VERSION_COMPATIBLE FALSE )

else()

	if( PACKAGE_FIND_VERSION STREQUAL PACKAGE_VERSION )
		set( PACKAGE_VERSION_EXACT TRUE )
	endif()

	if( PACKAGE_FIND_VERSION_MAJOR STREQUAL PACKAGE_VERSION_MAJOR )
		set( PACKAGE_VERSION_COMPATIBLE TRUE )
	else()
		set( PACKAGE_VERSION_COMPATIBLE FALSE )
	endif()
endif()
